# Generated by Django 5.1.1 on 2024-11-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=10, unique=True)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LectureRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=15, unique=True)),
                ('room_name', models.CharField(default='Lecture Room', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PEGymHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_id', models.CharField(max_length=15, unique=True)),
                ('hall_name', models.CharField(default='PE Hall', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('timeslot', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='CSPSyllabus',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=69)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('courses', models.ManyToManyField(to='scheduling.course')),
            ],
        ),
        migrations.CreateModel(
            name='CSPRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=30, null=True)),
                ('room_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_tags', models.ManyToManyField(to='scheduling.cspsyllabus')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.department'),
        ),
        migrations.CreateModel(
            name='ETPSyllabus',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=69)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('courses', models.ManyToManyField(to='scheduling.course')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_id', models.CharField(max_length=15, unique=True)),
                ('lab_name', models.CharField(default='Laboratory', max_length=64)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=15, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=64, null=True)),
                ('room_floor', models.IntegerField()),
                ('room_building', models.CharField(choices=[('CB MAIN', 'CB MAIN'), ('CBS SOUTH', 'CBS SOUTH'), ('CBE EAST', 'CBE EAST')], max_length=20)),
                ('is_laboratory', models.BooleanField(default=False)),
                ('department_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10, unique=True)),
                ('section_name', models.CharField(max_length=10)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=15)),
                ('subject_name', models.CharField(max_length=100, null=True)),
                ('semester', models.CharField(choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester')], default='1st Semester', max_length=50)),
                ('requires_laboratory', models.BooleanField(default=False)),
                ('year_level', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('days', models.CharField(choices=[('M / TH', 'M / TH'), ('M / W', 'M / W'), ('W / TH', 'W / TH'), ('T / F', 'T / F'), ('T / W', 'T / W'), ('M', 'M'), ('T', 'T'), ('W', 'W'), ('TH', 'TH'), ('F', 'F'), ('SAT', 'SAT'), ('W / W', 'W / W')], max_length=12)),
                ('timeslot', models.CharField(default='07:30AM - 09:00AM', max_length=50)),
                ('starttime', models.CharField(blank=True, max_length=24, null=True)),
                ('room_preference', models.CharField(blank=True, choices=[('Lecture Room', 'Lecture Room'), ('PE Hall', 'PE Hall'), ('Gym Hall', 'Gym Hall'), ('Civil Engineering Lab', 'Civil Engineering Lab'), ('JEEP Start', 'JEEP Start'), ('JEEP Accelerate', 'JEEP Accelerate'), ('Nursing Lab', 'Nursing Lab'), ('Human Anatomy Simulation Center', 'Human Anatomy Simulation Center'), ('Computer Laboratory', 'Computer Laboratory'), ('EIRC', 'EIRC'), ('DSAC', 'DSAC'), ('TBI MOESIS', 'TBI MOESIS'), ('ETP Drawing Room', 'ETP Drawing Room'), ('Chemistry Lab', 'Chemistry Lab'), ('Biology Room', 'Biology Room'), ('Criminology Lab', 'Criminology Lab'), ('Criminology Lecture Room', 'Criminology Lecture Room'), ('Hotel de Saturnino', 'Hotel de Saturnino'), ('Physics Lab', 'Physics Lab'), ('Kitchen', 'Kitchen'), ('Drawing Room', 'Drawing Room')], default='Lecture Room', max_length=64, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduling.section')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ManyToManyField(to='scheduling.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
                ('section', models.ManyToManyField(to='scheduling.section')),
                ('subject_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='contenttypes.contenttype')),
                ('timeslots', models.ManyToManyField(to='scheduling.timeslot')),
            ],
        ),
    ]
