# Generated by Django 5.1.1 on 2024-10-09 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.CharField(max_length=10, unique=True)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=15, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=64, null=True)),
                ('room_floor', models.IntegerField(max_length=4)),
                ('room_building', models.CharField(choices=[('CB MAIN', 'CB MAIN'), ('CBS SOUTH', 'CBS SOUTH'), ('CBE EAST', 'CBE EAST')], max_length=20)),
                ('is_laboratory', models.BooleanField(blank=True, null=True)),
                ('department_priority', models.ManyToManyField(blank=True, null=True, to='scheduling.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=10, unique=True)),
                ('section_name', models.CharField(max_length=10)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=15)),
                ('subject_name', models.CharField(max_length=100, null=True)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True)),
                ('requires_laboratory', models.BooleanField(blank=True, null=True)),
                ('subject_type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor')], max_length=6)),
                ('days', models.CharField(choices=[('M/TH', 'M/TH'), ('T/F', 'T/F'), ('W', 'W'), ('SAT', 'SAT')], max_length=6)),
                ('timeslot', models.CharField(default='7:30AM-9:00AM', max_length=10)),
                ('weekly_duration', models.FloatField(blank=True, default=3, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.section')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.IntegerField(max_length=20)),
                ('name', models.CharField(max_length=100, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
                ('expertise', models.ManyToManyField(to='scheduling.subject')),
            ],
        ),
    ]
