# Generated by Django 5.1.1 on 2024-10-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_floor',
            field=models.IntegerField(),
        ),
    ]
