# Generated by Django 5.1.1 on 2024-11-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cspsyllabus',
            name='has_lab',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='etpsyllabus',
            name='has_lab',
            field=models.BooleanField(default=True),
        ),
    ]
