# Generated by Django 5.1.1 on 2024-10-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_instructor_instructor_id_alter_room_room_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='department_priority',
            field=models.ManyToManyField(blank=True, to='scheduling.department'),
        ),
    ]
