# Generated by Django 5.1.1 on 2024-10-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_room_department_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='department_priority',
        ),
        migrations.AddField(
            model_name='room',
            name='course_priority',
            field=models.ManyToManyField(blank=True, to='scheduling.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='timeslot',
            field=models.CharField(default='7:30AM - 9:00AM', max_length=10),
        ),
    ]
