# Generated by Django 5.1.1 on 2024-10-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_remove_room_department_priority_room_course_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ManyToManyField(blank=True, to='scheduling.course'),
        ),
    ]
