# Generated by Django 5.1.1 on 2024-10-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_remove_subject_course_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='course_priority',
        ),
        migrations.AddField(
            model_name='room',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='scheduling.course'),
        ),
        migrations.AddField(
            model_name='room',
            name='priority',
            field=models.CharField(default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_laboratory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='requires_laboratory',
            field=models.BooleanField(default=False),
        ),
    ]
