# Generated by Django 5.1.1 on 2024-10-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_remove_subject_subject_type_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='days',
            field=models.CharField(choices=[('M / TH', 'M / TH'), ('M / W', 'M / W'), ('W / TH', 'W / TH'), ('T / F', 'T / F'), ('T / W', 'T / W'), ('M', 'M'), ('T', 'T'), ('W', 'W'), ('TH', 'TH'), ('F', 'F'), ('SAT', 'SAT'), ('W / W', 'W / W')], max_length=12),
        ),
    ]
