# Generated by Django 5.1.1 on 2024-10-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_remove_subject_course_subject_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='room_preference',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
