# Generated by Django 5.1.1 on 2024-10-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0017_alter_subject_room_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('timeslot', models.CharField(max_length=34)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=20)),
                ('subject_name', models.CharField(max_length=64)),
                ('rooms', models.ManyToManyField(to='scheduling.room')),
                ('sections', models.ManyToManyField(to='scheduling.section')),
                ('timeslot', models.ManyToManyField(to='scheduling.timeslot')),
            ],
        ),
    ]
