# Generated by Django 5.1.1 on 2024-11-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0020_alter_laboratories_lab_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='starttime',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='timeslot',
            field=models.CharField(default='07:30AM - 09:00AM', max_length=50),
        ),
    ]
