# Generated by Django 5.1.1 on 2024-11-22 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0021_subject_starttime_alter_subject_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=69, unique=True)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('courses', models.ManyToManyField(to='scheduling.course')),
            ],
        ),
        migrations.CreateModel(
            name='CSPRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=30, null=True)),
                ('room_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_tags', models.ManyToManyField(to='scheduling.cspsyllabus')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
                ('section', models.ManyToManyField(to='scheduling.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.cspsyllabus')),
                ('timeslots', models.ManyToManyField(to='scheduling.timeslot')),
            ],
        ),
    ]
