# Generated by Django 5.1.1 on 2024-11-23 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0026_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
