# Generated by Django 5.1.1 on 2024-11-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0027_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectsession',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='subjectsession',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='subjectsession',
            name='timeslot',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='SubjectSession',
        ),
    ]
