# Generated by Django 5.1.1 on 2024-11-25 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0028_remove_subjectsession_rooms_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='MajorSession',
        ),
        migrations.CreateModel(
            name='MajorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=69)),
                ('year_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)])),
                ('need_lab', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='scheduling.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.department')),
            ],
        ),
        migrations.CreateModel(
            name='ETPRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=10, unique=True)),
                ('room_name', models.CharField(blank=True, max_length=30, null=True)),
                ('room_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_tags', models.ManyToManyField(to='scheduling.majorsubject')),
            ],
        ),
        migrations.AlterField(
            model_name='csproom',
            name='subject_tags',
            field=models.ManyToManyField(to='scheduling.majorsubject'),
        ),
        migrations.AlterField(
            model_name='majorsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.majorsubject'),
        ),
    ]
