# Generated by Django 5.1.1 on 2024-11-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0029_rename_session_majorsession_majorsubject_etproom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cspsyllabus',
            name='subject_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='majorsubject',
            name='subject_code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
