# Generated by Django 5.1.1 on 2024-11-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0030_alter_cspsyllabus_subject_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='majorsession',
            name='course',
        ),
    ]
